language: perl
matrix:
  include:
    - perl: "5.28"
      dist: xenial
    - perl: "5.26"
      dist: xenial
    - perl: "5.24"
      dist: xenial
    - perl: "5.22"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.12"
      dist: trusty
    #powerjobs
    - perl: "5.28"
      dist: xenial
      arch: ppc64le
    - perl: "5.26"
      dist: xenial
      arch: ppc64le
    - perl: "5.24"
      dist: xenial
      arch: ppc64le
    - perl: "5.22"
      dist: xenial
      arch: ppc64le
    - perl: "5.20"
      dist: trusty
      arch: ppc64le
    - perl: "5.18"
      dist: trusty
      arch: ppc64le
    - perl: "5.16"
      dist: trusty
      arch: ppc64le
    - perl: "5.14"
      dist: trusty
      arch: ppc64le
    - perl: "5.12"
      dist: trusty
      arch: ppc64le
    
install:
  - cpanm --local-lib=~/perl5 local::lib
  - cpanm --local-lib=~/perl5 --quiet --notest --skip-satisfied Devel::Cover
  - cpanm --local-lib=~/perl5 --quiet --notest --skip-satisfied Module::Build
  - cpanm --local-lib=~/perl5 --quiet --installdeps --notest --force --skip-satisfied .
script:
  - export PERL5LIB=$HOME/perl5/lib/perl5
  - export PATH=$HOME/perl5/bin:$PATH
  - perl Build.PL && ./Build build && cover -test
after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1
sudo: false

#default is "xenial" which does not support perl versions older than 5.22
dist: bionic
